package csv.migrator.model

data class Iserve(
    override val managerTubNumber: String?,
    override var managerLogin: String?,
    override var crmLogin: String?,

    val MKK_ROLE: String?,
    val active: String?,
    val chief: String?,
    val code: String?,
    val crmId: String?,
    val dataId: String?,
    val description: String?,
    val emailAlpha: String?,
    val emailSigma: String?,
    val functionalUnit: String?,
    val id: String?,
    val isPilot: String?,
    val latitude: String?,
    val longitude: String?,
    val managerFIO: String?,
    val managerPhone: String?,
    val nameArea: String?,
    val namePlace: String?,
    val nameStreet: String?,
    val numBldg: String?,
    val numCorps: String?,
    val numHouse: String?,
    val numVlad: String?,
    val parentListId: String?,
    val parentValueId: String?,
    val regionCode: String?,
    val role: String?,
    val subIndex: String?,
    val subjFeder: String?,
    val subjFederCode: String?,
    val terbankCode: String?,
    val territorialBank: String?,
    val territorialUnit: String?,
    val typePlace: String?,
    val upgradeDate: String?,
    val value: String?,
    val valueId: String?,
    val versionId: String?,
    val vspNum: String?,
    val workPhone: String?,
    val workPhoneExt: String?
): Manager